server:
  port: 80
zuul:
  routes:
    shop:
      path: /shop/**
      url: forward:/api/v1/product
spring:
 datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://localhost:5432/rest-online-store
   username: postgres
   password: postgrespass
 jpa:
   show-sql: true
   properties:
     hibernate:
       format-sql: true
